#!/bin/bash
## (c) Denis Kaganovich
## v3.4

#BUS="pci"
BUS="\w+"

STR="^(?:static\s+)?(?:const\s+)?struct\s+"

fnd(){
grep -Prhl "${STR}${BUS}_device_id\s+" $1 --include="*.c" | while read i ; do
	local bus=`grep -Prho "${STR}${BUS}_device_id.*\s+" $i`
	bus="${bus#*struct }"
	local n="${bus%%[*}"
	n="${n%%=*}"
	n="${n##*device_id }"
	n="${n// }"
	bus="${bus%%_device_id*}"
	grep -Pq "^module_init\s*\(" $i || continue
	grep -q "MODULE_DEVICE_TABLE" $i && continue
	local ii="${i#$1}"
	ii="${ii#/}"
	case $ii in
	*/scx200_acb.c|*/pch_dma.c) if ! grep -q "^[ 	]*{ 0, }[,]*$" "$i"; then
		echo "BROKEN: $bus: $ii"
		continue
	fi
	;;
	*/mdio-gpio.c) # ,{0, 0}
		echo "BROKEN: $bus: $ii"
		continue
	;;
	*/rtc-mc13xxx.c|*/i2c-eg20t.c)
		echo "BROKEN: $bus: $ii"
		continue
	;;
	*/hil_mlc.c) # ,{0} or unused
		echo "BROKEN/SKIPPED: $bus: $ii"
		continue
	;;
	*/neo1973_wm8753.c)
		echo "SKIPPED: $bus: $ii"
		continue
	;;
	esac
	if [[ "$2" != "f" ]] ; then
		local b="$bus"
		case $b in
			of) b="of_platform";;
		esac
		grep -Pq "${STR}${b}_driver\s+" $i || {
			echo "UNSURE: $bus: $ii"
			continue
		}
	fi
	bus="${bus%%_*}"
	local BU
	case "$bus" in
	sdio)BU=MMC;;
	rio)BU=RAPIDIO;;
	*)BU="${bus^^}";;
	esac
	if [[ "$2" != "f" ]] && ! grep -Pqr "MODULE_DEVICE_TABLE\($bus," $1 --include="*.c" ; then
		echo "UNKNOWN BUS: $bus ($ii)"
	elif grep -Prq "^\s*(?:menu)?config\s+$BU(?:\s.*)?$" $1 --include="Kconfig*"; then
		echo "Fixing: $BU: ($n) $ii"
		sed -i -e 's/^\(module_init.*\)$/\n#ifdef CONFIG_'"$BU"'\nMODULE_DEVICE_TABLE('"$bus, $n"');\n#endif\n\n\1/' $i
	else
		echo "Fixing: $bus: ($n) $ii"
		sed -i -e 's/^\(module_init.*\)$/\nMODULE_DEVICE_TABLE('"$bus, $n"');\n\n\1/' $i
	fi
done
}

[[ -z "$1" ]] && echo "$0 <path_to_kernel> [f]" && exit 1

fnd $*
