#!/bin/sh
## (c) Denis Kaganovich
## v2

#BUS="pci"
BUS="\w+"

STR="^(?:static\s+)?(?:const\s+)?struct\s+"

fnd(){
grep -Prhl "${STR}${BUS}_device_id\s+" $1 --include="*.c" | while read i ; do
	local bus=`grep -Prho "${STR}${BUS}_device_id.*\s+" $i`
	bus="${bus#*struct }"
	local n="${bus%%[*}"
	n="${n%%=*}"
	n="${n##*device_id }"
	n="${n// }"
	bus="${bus%%_device_id*}"
	grep -Pq "^module_init\s*\(" $i || continue
	grep -q "MODULE_DEVICE_TABLE" $i && continue
	if [[ "$2" != "f" ]] || [[ "$bus" == "of" ]] ; then
		local b="$bus"
		# at least 1 broken under x86_64
#		case $b in
#			of) b="of_platform";;
#		esac
		grep -Pq "${STR}${b}_driver\s+" $i || {
			echo "UNSURE: $bus: $i"
			continue
		}
	fi
	bus="${bus%%_*}"
	local ii="${i#$1}"
	ii="${ii#/}"
	if [[ "$2" != "f" ]] && ! grep -Pqr "MODULE_DEVICE_TABLE\($bus," $1 --include="*.c" ; then
		echo "UNKNOWN BUS: $bus ($ii)"
	else
		echo "Fixing: $bus: ($n) $ii"
		sed -i -e 's/^\(module_init.*\)$/\nMODULE_DEVICE_TABLE('"$bus, $n"');\n\n\1/' $i
	fi
done
}

[[ -z "$1" ]] && echo "$0 <path_to_kernel> [f]" && exit 1

fnd $*
