#!/bin/sh
# simple dirty detect & embed modules for actual hardware
# v1.3
# (c) Denis Kaganovich, under Anarchy license

m2y(){
	grep -q "^$1=m$" .config || return
	echo $1
	$Y && sed -i -e "s:^$1=m\$:$1=y:" .config
	# buggy dependences only
	case "$1" in
	CONFIG_ACPI_VIDEO)m2y CONFIG_VIDEO_OUTPUT_CONTROL;;
	esac
}

findconf(){
local i
for i in "${@}"; do
	grep -Rh "^\s*obj\-\$[(]CONFIG_.*\s*\+=.*\s${i//[_-]/[_-]}\.o" . --include Makefile|while read i; do
		i="${i#*(}"
		m2y "${i%%)*}"
	done
done
}

fs(){
	local a b c d
	while read a b c d; do
		[[ "$b" == / ]] && [[ "$c" != rootfs ]] && echo "$c"
	done </proc/mounts
}

modaliases(){
local i
grep -sh "^MODALIAS=" $(find /sys -name uevent)|sed -e 's:^MODALIAS=::'|sort -u|while read i; do
modalias "$i"||continue
# strip "later" concurrent drivers
i="$ALIAS"
i="${ALIAS%%1 *}"
#[[ "$i" != "$ALIAS" ]] && [[ -n "$i" ]] && echo "strip: $ALIAS" >&2
i="${i:-${ALIAS#1 }}"
echo "${i// /
}"
$Y && rm -f $i
done|sed -e 's:^.*/::g' -e 's:\.ko$::g' -e 's/-/_/g'|sort -u
}

help(){
echo "$0 <path_to_kernel/modules> {options}
	(default: -y -b -s)
	-y - actually fix .config
	-s - /sys modaliases (hardware)
	-b - root fs
	-r - runtime modules (loaded)"
exit 1
}

go(){
local i
for i in "${@}"; do
	case "$i" in
	-y)Y=true;;
	-s)
		[[ -e modules.alias.sh ]] || perl /usr/share/genpnprd/mod2sh.pl . >/dev/null || {
			echo "Unable to run '/usr/share/genpnprd/mod2sh.pl'" >&2
			exit 1
		}
		. ./modules.alias.sh
		findconf `modaliases`
	;;
	-b)
		i=`fs`
		findconf "$i"
		m2y "CONFIG_${i^^}_FS"
	;;
	-r)findconf `ls -1 /sys/module`;;
	*)help >&2;;
	esac
done
}

[[ -n "$1" ]] && cd "$1" || help
shift
Y=false
case "$*" in
-y)go -y -s -b;;
?*)go "${@}";;
*)go -s -b;;
esac
