#!/bin/sh
# fsck wrapper to initrd:chroot via /newroot

ex(){
	umount /newroot/sys 2>/dev/null
	umount /newroot/proc 2>/dev/null
	exit ${1:-8}
}

mount -t proc proc /newroot/proc || ex
mount -t sysfs sysfs /newroot/sys || ex
chroot /newroot /sbin/fsck "${@}"
ex  $?


