#!/bin/sh
# some of busyboxes dont have mdev, some - mdev.conf|/dev/input/
# mdev -h

DROOT=false
DETECTBLK=false
Q=-qs
O=/dev/null

mdevs(){
	[[ -e "$1" ]] && for i in $*; do
		local DEVNAME="" MAJOR="" MINOR="" FIRMWARE="" DEVPATH="" DEVMODE=""
		eval "$(sed -e 's:^\(.*\)=\([^"].*[^"]\)$:\1="\2":g' -e 's/^[^=]*$//g' <"$i")" || echo "! $i"
		i="${i#/sys/class/}"
		[[ -e "/dev/$DEVNAME" ]] || _mdev "${i%%/*}"
	done
}

modprobe(){
	local i m c
	read m </proc/sys/kernel/modprobe && [[ -x "$m" ]] || m="busybox modprobe"
	if [[ "$2" == "-a" ]] && ! $m -V -a >/dev/null 2>&1; then
		shift 2
		for i in "${@}"; do
			$m $Q "$i"
		done
	else
		$m $Q "${@}"
	fi
}

modmdev(){
	[[ -z "$MODALIAS" ]] || echo "$MODALIAS" 2>/dev/null >>/etc/modalias || {
		loadsh modprobe
		modprobe "${@}" $MODALIAS 2>>$O
	}
}

loadsh(){
	[[ "${SHLOADED##* $1 }" == "${SHLOADED}" ]] &&
		[[ -e /etc/$1.sh ]] && . /etc/$1.sh && SHLOADED="$SHLOADED $1 "
	return $?
}

_mdev(){
local i t=c
case "$1:$ACTION" in
block:*)t=b;;
*:remove)
	rm "/dev/$DEVNAME"
	return
;;
*:add)modmdev --;;
esac
if [[ -n "$DEVNAME" ]] && ! [[ -e "/dev/$DEVNAME" ]]; then
	DEVNAME="/dev/$DEVNAME"
	i="${DEVNAME%/*}"
	[[ -e "$i" ]] || mkdir -p "$i"
	mknod -m ${DEVMODE:-0600} "$DEVNAME" $t $MAJOR $MINOR && [[ $t == b ]] && [[ "`cat "/sys/block${DEVNAME#/dev}/size" 2>/dev/null`" != 0 ]] && if $DETECTBLK || [[ -d /etc/modalias ]]; then
		loadsh blkid
		: ${KV:=`uname -r`}
		local id="`blkid $DEVNAME`" d p o t x
		MODALIAS=$(for i in `echo "$id"|grep ":.* TYPE="|sed -e 's:^.* TYPE="\([^"]*\)".*$:\1:g'|sort -u`; do # "
			grep -q "	$i$" /proc/filesystems && continue
			find /lib/modules/$KV/ /lib/modules/$KV/kernel/|grep "/$i/.*\.ko\$\|$i\.ko\$"|sed -e 's:^.*/::g' -e 's:\.ko$::g'|sort -u
		done)
		modmdev $Q -a
		echo "$id"|while read i; do
			eval "set $i"
			shift
			while read d p t o x; do
				[[ -n "${d%%\#*}" ]] && for i in $DEVNAME "${@}"; do
					[[ "$d" == "$i" ]] || [[ "$d:$p" == "auto:/newroot" ]] || continue
					if [[ "$p" == /newroot ]]; then
					    ( $DROOT && mkdir $p && (
						mount -o "${o:-ro}" -t "${t:-auto}" $DEVNAME $p && ( [[ -e $p/sbin/init ]] &&
						grep -q "^$DEVNAME[ 	][ 	]*/[ 	]" $p/etc/fstab || (
						umount $p;false ) ) || rmdir $p ) ) 2>>$O
					else
						mount -o "${o:-ro}" -t "${t:-auto}" $DEVNAME $p
					fi
				done
			done </etc/fstab
		done
	fi
fi
if [[ -n "$FIRMWARE" ]] && echo 1 >/sys/$DEVPATH/loading; then
	[[ -e /lib/firmware/$FIRMWARE ]] && cat /lib/firmware/$FIRMWARE >/sys/$DEVPATH/data && echo 0 >/sys/$DEVPATH/loading || echo -1 >/sys/$DEVPATH/loading
fi
}

mdev(){
local i j
while [[ -n "$*" ]]; do
case "$1" in
-v|-vs)Q=$1;O=/dev/console;;
-q|-qs)Q=$1;O=/dev/null;;
-b)DETECTBLK=true;;
-m|-i|-M)
	i=/etc/modalias
	loadsh modprobe
	[[ "$1" == "-m" ]] && modprobe $Q -a `echo ""|grep -sh "^MODALIAS=" $(find /sys -name uevent -print|sort)|sed -e 's:^MODALIAS=::g'|uniq` 2>>$O
	while ! ( [[ "$1" == "-i" ]] && ln -s /sys $i 2>/dev/null ) && [[ -f $i ]] && mv $i ${i}_ ; do
		modprobe $Q -a `cat ${i}_` 2>>$O
		rm ${i}_
	done
;;
-w)	MODALIAS=scsi_wait_scan
	modmdev $Q
;;
-s)
	shift
	for i in "${@:-"*"}"; do
		case "$i" in
		-*)mdev $i;;
		*)mdevs /sys/class/$i/*/uevent;;
		esac
	done
	return
;;
-all)mdev -s mem -b "*" -m -i;;
-*init)
	DROOT=true
	/bin/busybox mount /proc||mount /proc
	/bin/busybox --install -s
	mount /sys
	mdev -b -s mem -i block
	mount -a 2>>$O
	SHLOADED=""
	mkdir -p /temp/cache/modprobe
	i="-"
	while ! ( [[ $1 == -fastinit ]] && [[ -e /newroot ]] ) && j=`cat /proc/modules` && [[ "$i" != "$j" ]]; do
		mdev -m -w -s block
		i="$j"
	done
	[[ -e /sys/module/drm_kms_helper ]] && modprobe $Q fbcon 2>>$O
	j=0
	for i in /sys/module/*; do
		let j=j+1
	done
	echo "$j modules"
	cd /newroot && {
		umount /* 2>>$O
		mount
		exec /sbin/switch_root -c /dev/console /newroot /sbin/init
	}
	shift
	[[ -z "$*" ]] && return
	ln -s $0 /sbin/hotplug
	mdev -s "*" -i
	exec "${@}"
;;
-*)echo 'mdev replacement, (c) Denis Kaganovich, under Anarchy or GPLv2 license
Named "hotplug" will detect /newroot, "mdev" - no, "*init|*rc" - initrc.
Options:
-s [c]	populate /dev from /sys/class/[c]
-v|q[s]	output
-b	modprobe new fs
-m	scan+modprobe modaliases
-i	install: modaliases to background
-w	scsi_wait_scan
-all	= mdev -s mem -b "*" -m -i
-[fast]init	initrc
Example: mdev -s "*" -m'
return
;;
*)_mdev $1;;
esac
[[ -e /sys/module/scsi_wait_scan ]] && rmmod scsi_wait_scan
shift
done
}

case $0 in
*rc|*init)mdev -init /bin/sh;;
*hotplug*)DROOT=true;mdev "${@}";;
*mdev*)mdev "${@}";;
esac
