#!/bin/sh
# some of busyboxes dont have mdev, some - mdev.conf|/dev/input/
# mdev -h

DETECTBLK=false
Q=-qs

mdevs(){
	[[ -e "$1" ]] && for i in $*; do
		local DEVNAME="" MAJOR="" MINOR="" FIRMWARE="" DEVPATH="" DEVMODE=""
		eval "$(sed -e 's:^\(.*\)=\([^"].*[^"]\)$:\1="\2":g' -e 's/^[^=]*$//g' <"$i")" || echo "! $i"
		i="${i#/sys/class/}"
		[[ -e "/dev/$DEVNAME" ]] || _mdev "${i%%/*}"
	done
}

modprobe(){
	local i m
	read m </proc/sys/kernel/modprobe && if [[ "$2" == "-a" ]] && ! $m -V -a >/dev/null 2>&1; then
		shift 2
		for i in "${@}"; do
			$m $Q "$i"
		done
	else
		$m $Q "${@}"
	fi
}

modmdev(){
	[[ -z "$MODALIAS" ]] || echo "$MODALIAS" >>/etc/modalias 2>/dev/null || {
		loadsh modprobe
		modprobe "${@}" $MODALIAS
	}
}

loadsh(){
	[[ "${SHLOADED##* $1 }" == "${SHLOADED}" ]] &&
		[[ -e /etc/$1.sh ]] && . /etc/$1.sh && SHLOADED="$SHLOADED $1 "
	return $?
}

_mdev(){
local i t=c
case "$1:$ACTION" in
block:*)t=b;;
*:remove)
	rm "/dev/$DEVNAME"
	return
;;
*:add)modmdev --;;
esac
if [[ -n "$DEVNAME" ]] && ! [[ -e "/dev/$DEVNAME" ]]; then
	DEVNAME="/dev/$DEVNAME"
	i="${DEVNAME%/*}"
	[[ -e "$i" ]] || mkdir -p "$i"
	mknod -m ${DEVMODE:-0600} "$DEVNAME" $t $MAJOR $MINOR && [[ $t == b ]] && if $DETECTBLK || [[ -d /etc/modalias ]]; then
		loadsh blkid
		: ${KV:=`uname -r`}
		MODALIAS=$(for i in `blkid $DEVNAME|grep ":.* TYPE="|sed -e 's:^.* TYPE="\([^"]*\)".*$:\1:g'|sort -u`; do # "
			grep -q "	$i$" /proc/filesystems && continue
			find /lib/modules/$KV/ /lib/modules/$KV/kernel/|grep "/$i/.*\.ko\$\|$i\.ko\$"|sed -e 's:^.*/::g' -e 's:\.ko$::g'|sort -u
		done)
		modmdev $Q -a
	fi
	mount -a 2>/dev/null
fi
if [[ -n "$FIRMWARE" ]] && echo 1 >/sys/$DEVPATH/loading; then
	[[ -e /lib/firmware/$FIRMWARE ]] && cat /lib/firmware/$FIRMWARE >/sys/$DEVPATH/data && echo 0 >/sys/$DEVPATH/loading || echo -1 >/sys/$DEVPATH/loading
fi
}

mdev(){
local i
while [[ -n "$*" ]]; do
case "$1" in
-[vq]|-[vq]s)Q=$1;;
-b)DETECTBLK=true;;
-m|-i|-M)
	i=/etc/modalias
	loadsh modprobe
	[[ "$1" == "-m" ]] && modprobe $Q -a `echo ""|grep -sh "^MODALIAS=" $(find /sys -name uevent -print|sort)|sed -e 's:^MODALIAS=::g'|uniq`
	while ! ( [[ "$1" == "-i" ]] && ln -s /sys $i 2>/dev/null ) && [[ -f $i ]] && mv $i ${i}_ ; do
		modprobe $Q -a `cat ${i}_`
		rm ${i}_
	done
;;
-s)
	shift
	for i in "${@:-"*"}"; do
		case "$i" in
		-*)mdev $i;;
		*)mdevs /sys/class/$i/*/uevent;;
		esac
	done
	return
;;
-all)mdev -s mem -b "*" -m -i;;
-init)
	/bin/busybox mount -t proc proc /proc||mount -t proc proc /proc
	/bin/busybox --install -s
	mdev -M -s mem -b block
	mount -a 2>/dev/null
	SHLOADED=""
	echo /sbin/modprobe >/proc/sys/kernel/modprobe
	mdev -s -m block -M
	[[ -e /sys/module/drm_kms_helper ]] && modprobe fbcon
	/sbin/switch_root -c /dev/console /new_root /sbin/init
	shift
	[[ -z "$*" ]] && return
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	mdev -s "*" -i
	exec "${@}"
;;
-*)echo 'mdev replacement, (c) Denis Kaganovich, under Anarchy or GPLv2 license
Options:
-s [c]	populate /dev from /sys/class/[c]
-v|q[s]	modprobe output
-b	modprobe new fs
-m	scan+modprobe modaliases
-i	install: modaliases to background
-all	= mdev -s mem -b "*" -m -i
-init	initrc
Example: mdev -s "*" -m'
return
;;
*)_mdev $1;;
esac
shift
done
}

case $0 in
*mdev*)mdev "${@}";;
*rc|*init)mdev -init /bin/sh;;
esac
