#!/bin/sh
# mdev replacement, (c) Denis Kaganovich, under Anarchy or GPLv2 license
# some of busyboxes don't have mdev, some - mdev.conf|/dev/input/
# Detect all: mdev -s "*" -m
# or: mdev -s "*" -i (& do not writable /etc/modalias -> modprobe via mdev)

mdevs(){
	for i in $*; do
		local DEVNAME="" MAJOR="" MINOR="" FIRMWARE="" DEVPATH="" DEVMODE=""
		eval "$(sed -e 's:^\(.*\)=\([^"].*[^"]\)$:\1="\2":g' -e 's/^[^=]*$//g' <"$i")" || echo "== $i"
		i="${i#/sys/class/}"
		mdev "${i%%/*}"
	done
}

modprobe(){
	/sbin/modprobe "${@}"
}

mdev(){
local i t=c
case "$1" in
block) t=b ;;
-m|-i)
	[[ -e /etc/modprobe.sh ]] && . /etc/modprobe.sh
	modprobe -q -a `echo ""|grep -sh "^MODALIAS=" $(find /sys -name uevent -print|sort)|sed -e 's:^MODALIAS=::g'|uniq`
	while [[ -f /etc/modalias ]] && mv /etc/modalias /etc/modalias_ && ( [[ "$1" == "-m" ]] || ( ! ln -s /sys /etc/modalias && [[ -f /etc/modalias ]] ) ) ; do
		modprobe -q -a `cat /etc/modalias_`
		rm /etc/modalias_
	done
	return
;;
-s)
	shift
	for i in "${@:-"*"}"; do
		case "$i" in
		-*)mdev $i;;
		*)mdevs /sys/class/$i/*/uevent;;
		esac
	done
	return
;;
esac
case "$ACTION" in
remove)
	rm "/dev/$DEVNAME"
	return
;;
add)	if [[ -n "$MODALIAS" ]]; then
		echo "$MODALIAS" >>/etc/modalias || `cat /proc/sys/kernel/modprobe` -- $MODALIAS
	fi
;;
esac
if [[ -n "$DEVNAME" ]] && ! [[ -e "/dev/$DEVNAME" ]]; then
	DEVNAME="/dev/$DEVNAME"
	i="${DEVNAME%/*}"
	[[ -e "$i" ]] || mkdir -p "$i"
	mknod -m ${DEVMODE:-0600} "$DEVNAME" $t $MAJOR $MINOR
fi
if [[ -n "$FIRMWARE" ]] && echo 1 >/sys/$DEVPATH/loading; then
	[[ -e /lib/firmware/$FIRMWARE ]] && cat /lib/firmware/$FIRMWARE >/sys/$DEVPATH/data && echo 0 >/sys/$DEVPATH/loading || echo -1 >/sys/$DEVPATH/loading
fi
}

mdev "${@}"
